#!/bin/bash

MYSQL_LINK=/usr/local/mysql
MYSQL_PATH=/usr/local/mysql-5.5.27-osx10.6-x86_64/
MARIA_PATH=/usr/local/mariadb-5.5.25-tokudb-48630-darwin-x86_64/

sudo rm $MYSQL_LINK
sudo ln -s $MYSQL_PATH $MYSQL_LINK
sudo chown -R _mysql:_mysql $MYSQL_LINK
